import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {demoGraph} from '../../src/demo.js';
import {readFile} from 'node:fs/promises';

test.beforeEach(async({page})=>{await page.goto('./');});
async function list(page){await page.getByRole('button',{name:'Список',exact:true}).click();}
async function node(page,name){await page.locator('.list-card').filter({has:page.getByRole('heading',{name,exact:true})}).getByRole('button',{name:'Изменить',exact:true}).click();}
async function save(page){await page.locator('#inspector').getByRole('button',{name:'Сохранить',exact:true}).click();}
test('full workflow: failure, reserve route, source, undo/redo, knowledge, backup, import, safe snapshot',async({page})=>{
 await expect(page.locator('.node')).toHaveCount(8);await expect(page.locator('#stats')).toContainText('2/2');
 await page.locator('#failure-kind').selectOption('edge');await page.locator('#failure-item').selectOption('e6');await expect(page.locator('#analysis-result')).toContainText('Потерян путь к 1');await expect(page.locator('.node.key.lost')).toHaveCount(1);
 await page.locator('#failure-item').selectOption('e1');await expect(page.locator('#analysis-result')).toContainText('сохранили путь');
 await page.locator('#failure-item').selectOption('e6');
 await page.getByRole('button',{name:'+ Связь',exact:true}).click();await page.locator('[name=from]').selectOption('arrival');await page.locator('[name=to]').selectOption('rumor');await page.locator('#edge-label').fill('Слухи у рынка');await save(page);
 await page.getByRole('button',{name:'+ Связь',exact:true}).click();await page.locator('[name=from]').selectOption('rumor');await page.locator('[name=to]').selectOption('warehouse');await page.locator('#edge-label').fill('Ночная доставка масла');await save(page);
 await expect(page.locator('#analysis-result')).toContainText('сохранили путь');await page.locator('#undo').click();await expect(page.locator('#analysis-result')).toContainText('Потерян путь');await page.locator('#redo').click();await expect(page.locator('#analysis-result')).toContainText('сохранили путь');
 await page.locator('#failure-kind').selectOption('node');await page.locator('#failure-item').selectOption('arrival');await expect(page.locator('#analysis-result')).toContainText('Потерян путь к 2');
 await page.locator('#failure-kind').selectOption('none');await list(page);await node(page,'Судовой журнал');await page.locator('[name=status]').selectOption('found');await page.locator('[name=summary]').fill('Мы нашли журнал. Следующий шаг — насосная.');await page.locator('[name=notes]').fill('TOP_SECRET_SENTINEL');await save(page);
 await page.locator('[data-open-edge="e2"]').first().click();await page.locator('[name=status]').selectOption('found');await page.locator('#edge-label').fill('SECRET_EDGE_SENTINEL');await save(page);
 await page.getByRole('button',{name:'Снимок игрокам',exact:true}).click();await expect(page.locator('.player-preview')).toContainText('2 карточек');const playerDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать HTML-снимок'}).click();const html=await readFile(await(await playerDownload).path(),'utf8');expect(html).toContain('Мы нашли журнал');for(const word of ['TOP_SECRET_SENTINEL','SECRET_EDGE_SENTINEL','Капитана можно спасти','Гадалка у рынка','Квитанция на масло'])expect(html).not.toContain(word);await page.getByRole('button',{name:'Закрыть окно'}).click();
 await page.getByRole('button',{name:'Дело и копии'}).click();const backupDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать JSON'}).click();const backup=await readFile(await(await backupDownload).path(),'utf8');expect(backup).toContain('TOP_SECRET_SENTINEL');
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Пустое дело',exact:true}).click();await expect(page.locator('.list-card')).toHaveCount(0);
 await page.getByRole('button',{name:'Дело и копии'}).click();page.once('dialog',d=>d.accept());await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backup)});await expect(page.locator('.list-card')).toHaveCount(8);await expect(page.locator('#stats')).toContainText('2раскрыто');await page.reload();await expect(page.locator('#saved')).toContainText('Восстановлено');
});
test('node and edge CRUD, history, positions, key/start and unavailable',async({page})=>{
 await page.getByRole('button',{name:'+ Карточка',exact:true}).click();await page.locator('#node-title').fill('Новый свидетель');await page.locator('[name=type]').selectOption('person');await page.locator('[name=key]').check();await page.locator('[name=start]').check();await page.locator('details summary').filter({hasText:'Положение'}).click();await page.locator('[name=x]').fill('500');await page.locator('[name=y]').fill('650');await save(page);await expect(page.locator('.node')).toHaveCount(9);
 await page.locator('#node-title').fill('Свидетель у ворот');await save(page);await expect(page.locator('.node-title')).toContainText(['Свидетель у ворот']);
 await page.getByRole('button',{name:'+ Связь из карточки'}).click();await page.locator('[name=to]').selectOption('rescue');await page.locator('#edge-label').fill('Свидетельство');await save(page);await page.locator('[name=status]').selectOption('unavailable');await save(page);await expect(page.locator('.thread.unavailable')).toHaveCount(1);
 page.once('dialog',d=>d.accept());await page.locator('#delete-edge').click();await expect(page.locator('.thread')).toHaveCount(7);await page.locator('#undo').click();await expect(page.locator('.thread')).toHaveCount(8);
 await list(page);await node(page,'Свидетель у ворот');await page.locator('[name=status]').selectOption('unavailable');await save(page);await expect(page.locator('#analysis-result')).toContainText('Уже нет пути');page.once('dialog',d=>d.accept());await page.locator('#delete-node').click();await expect(page.locator('.list-card')).toHaveCount(8);await expect(page.locator('.thread')).toHaveCount(7);await page.locator('#undo').click();await expect(page.locator('.list-card')).toHaveCount(9);
});
test('bad import leaves campaign intact; XSS rendered as text and export inert',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.getByRole('button',{name:'Дело и копии'}).click();await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await expect(page.locator('#toast')).toContainText('JSON');await expect(page.locator('.node')).toHaveCount(8);
 const g=demoGraph();g.title='<img src=x onerror="globalThis.pwned=true">';g.nodes[0].title='<svg onload="globalThis.pwned=true">';g.nodes[0].summary='</textarea><script>globalThis.pwned=true</script>';g.nodes[0].notes='<img src=x onerror="globalThis.pwned=true">';page.once('dialog',d=>d.accept());await page.locator('#import-file').setInputFiles({name:'xss.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(g))});await expect(page.locator('#case-title')).toContainText('<img');expect(await page.evaluate(()=>globalThis.pwned)).toBeUndefined();await list(page);await node(page,g.nodes[0].title);expect(await page.locator('[name=summary]').inputValue()).toContain('<script>');
 await page.getByRole('button',{name:'Снимок игрокам',exact:true}).click();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать HTML-снимок'}).click();const html=await readFile(await(await dl).path(),'utf8');const snapshot=await page.context().newPage();await snapshot.setContent(html);expect(await snapshot.evaluate(()=>globalThis.pwned)).toBeUndefined();expect(await snapshot.locator('script,img,svg').count()).toBe(0);expect(errors).toEqual([]);
});
test('analysis does not discard unsaved notes; keyboard undo respects text input',async({page})=>{
 await list(page);await node(page,'Пустой причал');await page.locator('[name=notes]').fill('Черновик не потерять');await page.locator('#failure-kind').selectOption('edge');await page.locator('#failure-item').selectOption('e6');await expect(page.locator('[name=notes]')).toHaveValue('Черновик не потерять');await save(page);await page.locator('#board-view').click();await page.locator('#board').focus();await page.keyboard.press('Control+z');await list(page);await node(page,'Пустой причал');expect(await page.locator('[name=notes]').inputValue()).not.toBe('Черновик не потерять');
});
test('desktop and mobile screenshots, accessibility, keyboard, no data network',async({page})=>{
 await expect(page.locator('.node')).toHaveCount(8);const desktop=await new AxeBuilder({page}).analyze();expect(desktop.violations).toEqual([]);await page.screenshot({path:'qa-local/desktop.png',fullPage:true});
 await page.locator('#board').focus();const before=await page.locator('#world').getAttribute('style');await page.keyboard.press('ArrowRight');expect(await page.locator('#world').getAttribute('style')).not.toBe(before);await page.keyboard.press('+');await page.locator('#fit').click();
 await page.setViewportSize({width:390,height:844});await expect(page.locator('#player-button')).toBeVisible();await page.screenshot({path:'qa-local/mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);const mobile=await new AxeBuilder({page}).analyze();expect(mobile.violations).toEqual([]);
 await page.getByRole('button',{name:'Список',exact:true}).click();await node(page,'Пустой причал');await page.locator('[name=status]').selectOption('unavailable');await save(page);await expect(page.locator('#analysis-result')).toContainText('Нет доступной стартовой');const requests=[];page.on('request',r=>requests.push(r.url()));await page.getByRole('button',{name:'Снимок игрокам',exact:true}).click();await page.getByRole('button',{name:'Закрыть окно'}).click();expect(requests).toEqual([]);
});
