import {LIMITS,TYPES,STATES,clone,parseGraph,validateGraph,analyze,fragileEdges,playerData,playerHtml,escapeHtml as h,createHistory} from './core.js';
import {demoGraph} from './demo.js';

const $=selector=>document.querySelector(selector), storageKey='krasnaya-nit:v1';
let initial=demoGraph(), storageError='', restored=false;
try {const saved=localStorage.getItem(storageKey);if(saved){initial=parseGraph(saved);restored=true;}} catch {storageError='Локальное сохранение недоступно или повреждено. Исходные данные не перезаписываются до первого изменения. Скачивайте JSON-копии.';}
const history=createHistory(initial);
let selected=null, draft=null, edgeDraft=null, dirty=false, view='board', failure=null, toastTimer;
let camera={x:0,y:0,z:1}, drag=null, suppressClick=false;
const graph=()=>history.current;
const id=()=>crypto.randomUUID();
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),6000);}
function saveLocal(){try{localStorage.setItem(storageKey,JSON.stringify(graph()));$('#saved').textContent='Сохранено в этом браузере';$('#storage-note').textContent='Данные хранятся локально. Очистка браузера удалит дело — сохраняйте JSON-копии.';}catch{$('#saved').textContent='Не сохранено · скачайте JSON';$('#storage-note').textContent='Браузер не смог сохранить дело. Скачайте JSON-копию перед закрытием.';toast('Изменение применено, но локальная запись не удалась. Скачайте JSON-копию.');}}
function commit(next){try{history.commit(validateGraph(next));draft=null;edgeDraft=null;dirty=false;saveLocal();render();return true;}catch(e){toast(e.message);return false;}}
function leaveEditor(){if(dirty&&!confirm('Оставить несохранённые правки формы? Сначала можно нажать «Сохранить».'))return false;dirty=false;draft=null;edgeDraft=null;renderInspector();return true;}
function focusInspector(){const heading=$('#inspector h2');heading.tabIndex=-1;heading.focus({preventScroll:true});if(innerWidth<=850)$('#inspector').scrollIntoView({block:'nearest'});}
function selectNode(nodeId){if(!leaveEditor())return;selected={kind:'node',id:nodeId};render();focusInspector();}
function selectEdge(edgeId){if(!leaveEditor())return;selected={kind:'edge',id:edgeId};render();focusInspector();}
function newNode(){if(!leaveEditor())return;if(graph().nodes.length>=LIMITS.nodes){toast(`Достигнут предел: ${LIMITS.nodes} карточек.`);return;}draft={id:id(),type:'scene',title:'',summary:'',notes:'',status:'hidden',start:false,key:false,x:view==='list'?(graph().nodes.length%4)*320:Math.max(-10000,Math.min(10000,Math.round((($('#board').clientWidth||900)/2-camera.x)/camera.z-129))),y:view==='list'?Math.floor(graph().nodes.length/4)*200:Math.max(-10000,Math.min(10000,Math.round((250-camera.y)/camera.z)))};selected=null;renderInspector();$('#node-title').focus();}
function newEdge(){if(!leaveEditor())return;if(graph().nodes.length<1){toast('Сначала добавьте карточку.');return;}if(graph().edges.length>=LIMITS.edges){toast(`Достигнут предел: ${LIMITS.edges} связей.`);return;}const from=selected?.kind==='node'?selected.id:graph().nodes[0].id;edgeDraft={id:id(),from,to:graph().nodes.find(n=>n.id!==from)?.id||from,label:'',status:'hidden'};selected=null;renderInspector();$('#edge-label').focus();}

function render(){
  if(selected?.kind==='node'&&!graph().nodes.some(n=>n.id===selected.id))selected=null;
  if(selected?.kind==='edge'&&!graph().edges.some(e=>e.id===selected.id))selected=null;
  if(failure&&!graph()[failure.kind==='node'?'nodes':'edges'].some(n=>n.id===failure.id)){failure=null;$('#failure-kind').value='none';}
  $('#case-title').textContent=graph().title||'Дело без названия';
  const a=analyze(graph(),failure), fragile=fragileEdges(graph());
  $('#stats').innerHTML=`<span><strong>${a.keys.filter(n=>a.reached.has(n.id)).length}/${a.keys.length}</strong>выводов достижимы</span><span><strong>${graph().nodes.filter(n=>n.status==='found').length}</strong>раскрыто</span><span class="accent"><strong>${fragile.length}</strong>уязвимых улик</span>`;
  $('#undo').disabled=!history.canUndo;$('#redo').disabled=!history.canRedo;
  renderBoard(a);renderList(a);renderAnalysis(a);if(!dirty)renderInspector();
}
function renderBoard(a){
  $('#cards').innerHTML=graph().nodes.map((n,i)=>`<button class="node ${n.status} ${n.key?'key':''} ${a.baseline.has(n.id)&&!a.reached.has(n.id)?'lost':''} ${selected?.id===n.id&&selected.kind==='node'?'selected':''} ${failure?.kind==='node'&&failure.id===n.id?'failed':''}" data-node="${h(n.id)}" style="left:${n.x}px;top:${n.y}px" aria-label="${h(n.title)}, ${TYPES[n.type]}, ${STATES[n.status]}${n.start?', старт':''}${n.key?', ключевой вывод':''}${!a.reached.has(n.id)?', нет пути от старта':''}"><span class="node-type"><span>${TYPES[n.type]}</span><span>${String(i+1).padStart(2,'0')}</span></span><span class="node-title">${h(n.title)}</span><span class="node-tags">${n.start?'<span>◇ Старт</span>':''}${n.key?'<span class="key-text">◆ Ключевой</span>':''}<span class="${n.status==='found'?'found-text':''}">${STATES[n.status]}</span>${a.baseline.has(n.id)&&!a.reached.has(n.id)?'<span class="lost-text">Нет пути</span>':''}</span></button>`).join('');
  drawEdges();transformCamera();
}
function edgePath(from,to){
  if(from.id===to.id)return `M ${from.x+210} ${from.y} C ${from.x+320} ${from.y-130},${from.x-60} ${from.y-130},${from.x+45} ${from.y}`;
  const forward=to.x>from.x, x1=from.x+(forward?258:0),y1=from.y+75,x2=to.x+(forward?0:258),y2=to.y+75, bend=Math.max(50,Math.abs(x2-x1)*.48);
  return `M ${x1} ${y1} C ${x1+(forward?bend:-bend)} ${y1},${x2+(forward?-bend:bend)} ${y2},${x2} ${y2}`;
}
function drawEdges(){const nodes=new Map(graph().nodes.map(n=>[n.id,n]));$('#edge-paths').innerHTML=graph().edges.map(e=>{let f=nodes.get(e.from),t=nodes.get(e.to);if(drag?.kind==='node'&&drag.preview){if(f.id===drag.id)f={...f,...drag.preview};if(t.id===drag.id)t={...t,...drag.preview};}const path=edgePath(f,t);return `<path class="thread ${e.status} ${failure?.kind==='edge'&&failure.id===e.id?'failed':''}" d="${path}"/><path class="edge-hit" d="${path}" data-edge="${h(e.id)}"><title>${h(e.label||'Улика без названия')}</title></path>`;}).join('');}
function renderList(a){$('#list').innerHTML=graph().nodes.length?graph().nodes.map(n=>`<article class="list-card ${a.baseline.has(n.id)&&!a.reached.has(n.id)?'lost':''}"><div class="list-card-title"><div><small>${TYPES[n.type]} · ${STATES[n.status]}${n.start?' · Старт':''}${n.key?' · Ключевой вывод':''}</small><h3>${h(n.title)}</h3></div><button data-open-node="${h(n.id)}">Изменить</button></div><p>${h(n.summary||'Текст для игроков ещё не записан.')}</p>${n.notes?`<details><summary class="secret-label">Заметки ведущего</summary><p>${h(n.notes)}</p></details>`:''}<small>${a.reached.has(n.id)?'Есть путь от старта':'Нет пути от старта'}</small><ul>${graph().edges.filter(e=>e.from===n.id).map(e=>`<li><button data-open-edge="${h(e.id)}">${h(e.label||'Без названия')} → ${h(graph().nodes.find(t=>t.id===e.to).title)}</button> · ${STATES[e.status]}</li>`).join('')}</ul></article>`).join(''):'<div class="empty">Дело пока пустое. Добавьте первую карточку и отметьте её как старт.</div>';}
function renderAnalysis(a){
  const kind=$('#failure-kind').value;
  $('#failure-item-label').hidden=kind==='none';$('#failure-item-caption').textContent=kind==='edge'?'Улика':'Источник';
  if(kind!=='none'){const items=graph()[kind==='node'?'nodes':'edges'];$('#failure-item').innerHTML=items.map(n=>`<option value="${h(n.id)}">${h(kind==='node'?n.title:(n.label||'Без названия')+' · '+graph().nodes.find(t=>t.id===n.from).title+' → '+graph().nodes.find(t=>t.id===n.to).title)}</option>`).join('');$('#failure-item').value=failure?.id||'';}
  const lost=a.lost.length, starts=graph().nodes.filter(n=>n.start&&n.status!=='unavailable');
  let title=lost?`Потерян путь к ${lost} ${lost===1?'ключевому выводу':'ключевым выводам'}`:failure?'Ключевые выводы сохранили путь':'Проверяем записанные пути';
  if(!starts.length)title='Нет доступной стартовой точки';
  const selectedFailure=failure?(failure.kind==='node'?graph().nodes.find(n=>n.id===failure.id)?.title:graph().edges.find(e=>e.id===failure.id)?.label):'';
  let detail=lost?`<p>Без «${h(selectedFailure||'этой улики')}» больше нет пути от доступных стартов:</p><ul>${a.lost.map(n=>`<li><strong>${h(n.title)}</strong></li>`).join('')}</ul>`:failure?'<p>Остаются другие записанные пути. Это проверка структуры дела, а не гарантия решения загадки игроками.</p>':'<p>Скрытые карточки участвуют в анализе. Недоступные карточки и связи исключены. Каждый путь считается достаточным сам по себе.</p>';
  if(lost&&a.cut.length)detail+=`<p>Граница обрыва: ${a.cut.map(c=>`«${h(c.edge.label||'Без названия')}» — ${h(c.reason.toLowerCase())}`).join('; ')}.</p>`;
  if(a.disconnected.length)detail+=`<p class="view-only">Уже нет пути в обычном ходе: ${a.disconnected.map(n=>h(n.title)).join(', ')}. Проверьте старты и доступность.</p>`;
  if(!a.keys.length)detail+='<p>Отметьте хотя бы одну карточку как ключевой вывод.</p>';
  if(!starts.length)detail+='<p>Откройте начальную сцену и включите «Стартовая точка».</p>';
  $('#analysis-result').innerHTML=`<div class="analysis-result-title ${lost||!starts.length?'warn':'ok'}">${title}</div><div class="analysis-detail">${detail}</div>`;
}
function options(values,selectedValue){return Object.entries(values).map(([value,label])=>`<option value="${value}" ${selectedValue===value?'selected':''}>${label}</option>`).join('');}
function renderInspector(){
  const selectedNode=selected?.kind==='node'?graph().nodes.find(n=>n.id===selected.id):null;
  const selectedEdge=selected?.kind==='edge'?graph().edges.find(e=>e.id===selected.id):null;
  const n=draft||selectedNode,e=edgeDraft||selectedEdge;
  if(n){$('#inspector').innerHTML=`<div class="inspector-top"><span class="eyebrow">${draft?'НОВАЯ КАРТОЧКА':'МАТЕРИАЛ ДЕЛА'}</span><button id="close-editor" aria-label="Закрыть карточку">×</button></div><h2>${draft?'Добавить зацепку':h(n.title)}</h2><form id="node-form" class="editor"><label>Название<input id="node-title" name="title" maxlength="120" required value="${h(n.title)}"></label><div class="two-col"><label>Тип<select name="type">${options(TYPES,n.type)}</select></label><label>Состояние<select name="status">${options(STATES,n.status)}</select></label></div><label class="check-row"><input type="checkbox" name="start" ${n.start?'checked':''}>Стартовая точка</label><label class="check-row"><input type="checkbox" name="key" ${n.key?'checked':''}>Ключевой вывод</label><label>Текст для игроков<textarea name="summary" maxlength="5000">${h(n.summary)}</textarea><span class="editor-hint">Попадёт в снимок, когда карточка раскрыта.</span></label><label class="secret-label">Заметки ведущего<textarea name="notes" maxlength="5000">${h(n.notes)}</textarea><span class="editor-hint">Никогда не включаются в снимок игрокам.</span></label><details><summary class="subtle">Положение на доске</summary><div class="two-col"><label>X<input name="x" type="number" min="-10000" max="10000" step="1" value="${Math.round(n.x)}"></label><label>Y<input name="y" type="number" min="-10000" max="10000" step="1" value="${Math.round(n.y)}"></label></div></details><div class="form-actions"><button type="submit" class="primary">Сохранить</button>${draft?'':`<button type="button" id="delete-node" class="danger">Удалить</button>`}</div></form>${draft?'':`<div class="section-label">СВЯЗИ КАРТОЧКИ</div><ul class="related-list">${graph().edges.filter(e=>e.from===n.id||e.to===n.id).map(e=>`<li><button data-open-edge="${h(e.id)}">${h(e.label||'Без названия')}<span>${h(graph().nodes.find(t=>t.id===e.from).title)} → ${h(graph().nodes.find(t=>t.id===e.to).title)} · ${STATES[e.status]}</span></button></li>`).join('')||'<li class="subtle">Связей пока нет.</li>'}</ul><button id="connect-from" class="quiet" style="margin-top:12px">+ Связь из карточки</button>`}`;
    $('#node-form').addEventListener('input',()=>dirty=true);$('#node-form').addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.currentTarget), next=clone(graph()),node={...n,title:f.get('title').trim(),type:f.get('type'),status:f.get('status'),start:f.has('start'),key:f.has('key'),summary:f.get('summary'),notes:f.get('notes'),x:Number(f.get('x')),y:Number(f.get('y'))};if(draft)next.nodes.push(node);else next.nodes=next.nodes.map(v=>v.id===n.id?node:v);selected={kind:'node',id:n.id};if(commit(next))toast('Карточка сохранена.');});
    $('#delete-node')?.addEventListener('click',()=>{const count=graph().edges.filter(e=>e.from===n.id||e.to===n.id).length;if(confirm(`Удалить «${n.title}»${count?` и связанные нити (${count})`:''}? Это можно отменить.`)){const next=clone(graph());next.nodes=next.nodes.filter(v=>v.id!==n.id);next.edges=next.edges.filter(e=>e.from!==n.id&&e.to!==n.id);selected=null;commit(next);toast('Карточка удалена. Можно отменить.');}});$('#connect-from')?.addEventListener('click',newEdge);
  }else if(e){$('#inspector').innerHTML=`<div class="inspector-top"><span class="eyebrow">${edgeDraft?'НОВАЯ СВЯЗЬ':'УЛИКА-СВЯЗЬ'}</span><button id="close-editor" aria-label="Закрыть связь">×</button></div><h2>Нить между зацепками</h2><p class="intro-copy">Направление показывает, откуда игроки могут прийти к следующей карточке.</p><form id="edge-form" class="editor"><label>Откуда<select name="from">${graph().nodes.map(n=>`<option value="${h(n.id)}" ${e.from===n.id?'selected':''}>${h(n.title)}</option>`).join('')}</select></label><label>Куда<select name="to">${graph().nodes.map(n=>`<option value="${h(n.id)}" ${e.to===n.id?'selected':''}>${h(n.title)}</option>`).join('')}</select></label><label>Название улики · только ведущему<input id="edge-label" name="label" maxlength="120" value="${h(e.label)}"></label><label>Состояние<select name="status">${options(STATES,e.status)}</select><span class="editor-hint">В снимке появится только раскрытая связь между раскрытыми карточками. Название улики исключается.</span></label><div class="form-actions"><button type="submit" class="primary">Сохранить</button>${edgeDraft?'':`<button id="delete-edge" type="button" class="danger">Удалить</button>`}</div></form>${edgeDraft?'':'<button id="test-edge" class="quiet" style="margin-top:22px">Проверить потерю этой улики</button>'}`;
    $('#edge-form').addEventListener('input',()=>dirty=true);$('#edge-form').addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.currentTarget),next=clone(graph()),edge={...e,from:f.get('from'),to:f.get('to'),label:f.get('label'),status:f.get('status')};if(edgeDraft)next.edges.push(edge);else next.edges=next.edges.map(v=>v.id===e.id?edge:v);selected={kind:'edge',id:e.id};if(commit(next))toast('Связь сохранена.');});$('#delete-edge')?.addEventListener('click',()=>{if(confirm('Удалить связь? Это можно отменить.')){const next=clone(graph());next.edges=next.edges.filter(v=>v.id!==e.id);selected=null;commit(next);toast('Связь удалена.');}});$('#test-edge')?.addEventListener('click',()=>{if(!leaveEditor())return;failure={kind:'edge',id:e.id};$('#failure-kind').value='edge';render();$('.analysis-panel').scrollIntoView({block:'nearest'});});
  }else{$('#inspector').innerHTML=`<span class="eyebrow">ВЕДУЩЕМУ НА ЗАМЕТКУ</span><h2>Дело держится<br>на зацепках</h2><p class="intro-copy">На причале исчез капитан. У вас две дороги к насосной — и одна хрупкая нить к его спасению.</p><ol class="workflow"><li><strong>Разложите материалы</strong>Сцены, люди, места и выводы. Нажмите карточку, чтобы записать детали.</li><li><strong>Проверьте обрыв</strong>Выберите улику «Квитанция на масло». Подсветятся выводы без пути.</li><li><strong>Оставьте след игрокам</strong>Отмечайте раскрытое и скачайте безопасный снимок.</li></ol><div class="tip"><strong>Попробуйте резервный путь.</strong><p>Соедините причал с гадалкой, а её — со складом. Потеря квитанции перестанет обрывать спасение.</p></div><div class="section-label">ПРАВИЛО АНАЛИЗА</div><p class="subtle">Все связи — альтернативные пути. Сложные условия и обязательные сочетания улик здесь не моделируются.</p>`;if(graph().title!=='Последний рейс «Чайки»'){$('#inspector').innerHTML=`<span class="eyebrow">РАБОЧИЙ ПОРЯДОК</span><h2>Ведите нить</h2><ol class="workflow"><li><strong>Отметьте начало</strong>Добавьте материалы и включите стартовые точки.</li><li><strong>Выберите ключевые выводы</strong>Протяните направленные связи и проверьте потерю улики или источника.</li><li><strong>Записывайте раскрытое</strong>Текст для игроков храните отдельно от заметок ведущего.</li></ol><div class="tip">Каждая связь — самостоятельный путь. Анализ не предсказывает решения игроков. Снимок скачивается файлом; совместного редактирования нет.</div>`;}}
  $('#close-editor')?.addEventListener('click',()=>{const previous=selected;if(leaveEditor()){selected=null;render();const trigger=previous?.kind==='node'?$(view==='board'?`[data-node="${previous.id}"]`:`[data-open-node="${previous.id}"]`):previous?.kind==='edge'?$(`[data-open-edge="${previous.id}"]`):$('#add-node');trigger?.focus({preventScroll:true});}});
}
function transformCamera(){$('#world').style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.z})`;$('#zoom-label').textContent=Math.round(camera.z*100)+'%';}
function fit(){if($('#board').hidden||!$('#board').clientWidth)return;if(!graph().nodes.length){camera={x:50,y:50,z:1};transformCamera();return;}const ns=graph().nodes,minX=Math.min(...ns.map(n=>n.x)),maxX=Math.max(...ns.map(n=>n.x+258)),minY=Math.min(...ns.map(n=>n.y)),maxY=Math.max(...ns.map(n=>n.y+160));const b=$('#board'),z=Math.min(1,(b.clientWidth-60)/(maxX-minX),(b.clientHeight-105)/(maxY-minY));camera={z:Math.max(.05,z),x:(b.clientWidth-(maxX-minX)*z)/2-minX*z,y:(b.clientHeight-55-(maxY-minY)*z)/2-minY*z};transformCamera();}
function zoom(factor,cx=$('#board').clientWidth/2,cy=$('#board').clientHeight/2){const next=Math.max(.05,Math.min(2,camera.z*factor)),ratio=next/camera.z;camera={z:next,x:cx-(cx-camera.x)*ratio,y:cy-(cy-camera.y)*ratio};transformCamera();}
function changeView(next){if(!leaveEditor())return;view=next;$('#board').hidden=next!=='board';$('#list').hidden=next!=='list';$('#board-view').setAttribute('aria-pressed',next==='board');$('#list-view').setAttribute('aria-pressed',next==='list');if(next==='board')fit();}
function stepHistory(direction){if(!leaveEditor())return;if(history[direction]()){selected=null;saveLocal();render();toast(direction==='undo'?'Последнее изменение отменено.':'Изменение повторено.');}}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function modal(title,content){$('#modal-content').innerHTML=`<div class="modal-header"><h2 id="modal-title">${h(title)}</h2><button id="close-modal" aria-label="Закрыть окно">×</button></div>${content}`;$('#close-modal').onclick=()=>$('#modal').close();$('#modal').showModal();}
function files(){modal('Дело и резервные копии',`<div class="file-options"><div class="file-option"><h3>Полная копия ведущего</h3><p>JSON включает все секреты и заметки. Храните его у себя и передавайте только ведущему. История отмены в копию не входит.</p><button id="backup" class="primary">Скачать JSON</button><button id="import-trigger">Импортировать JSON</button></div><div class="file-option"><h3>Начать другое дело</h3><p>Текущее дело будет заменено. Сначала сохраните копию; замену также можно отменить.</p><button id="new-case">Пустое дело</button><button id="reset-demo">Загрузить демо</button></div></div><p class="modal-note" style="margin-top:18px">Одна локальная доска на браузер. Приватные окна, очистка данных и другой адрес сайта используют отдельное хранилище. Несколько вкладок могут перезаписать изменения.</p>`);$('#backup').onclick=()=>{download(JSON.stringify(graph(),null,2),'krasnaya-nit-gm-backup.json','application/json');toast('Полная копия скачана. Она содержит секреты ведущего.');};$('#import-trigger').onclick=()=>$('#import-file').click();$('#new-case').onclick=()=>replace({version:1,title:'Новое расследование',nodes:[],edges:[]});$('#reset-demo').onclick=()=>replace(demoGraph());}
function replace(next){if(!leaveEditor())return;if(!confirm('Заменить текущее дело? Сохраните JSON-копию. Замену можно отменить.'))return;selected=null;failure=null;$('#failure-kind').value='none';if(commit(next)){$('#modal').close();fit();toast('Дело загружено. Замену можно отменить.');}}
function exportPlayer(){if(dirty){toast('Сохраните правки карточки перед снимком игрокам.');return;}const data=playerData(graph());modal('Записи для игроков',`<p>В файл попадут только раскрытые карточки и их тексты для игроков. Заметки ведущего, скрытые карточки и названия улик физически исключаются.</p><div class="player-preview"><span>${data.nodes.length} ${data.nodes.length===1?'карточка':'карточек'} · ${data.edges.length} известных связей</span>${data.nodes.length?`<ul>${data.nodes.map(n=>`<li>${h(n.title)}</li>`).join('')}</ul>`:'<p>Ничего ещё не раскрыто. Отметьте карточки перед экспортом.</p>'}</div><p class="modal-note">Название дела и текст для игроков считаются публичными. Проверьте, что вы сами не записали в них секреты. Названия известных связей в снимке не отображаются.</p><button id="download-player" class="primary">Скачать HTML-снимок</button><p class="modal-note" style="margin-top:14px">Поделитесь скачанным файлом. Его можно открыть без интернета; это отдельный снимок, он не обновляется.</p>`);$('#download-player').onclick=()=>{download(playerHtml(graph()),'krasnaya-nit-players.html','text/html;charset=utf-8');toast('Снимок для игроков скачан.');};}
function help(){modal('Как вести красную нить',`<ol class="help-steps"><li><strong>Запишите материалы.</strong> Создайте карточки сцен, людей, мест и выводов. Отметьте один или несколько доступных стартов и ключевые выводы.</li><li><strong>Свяжите уликами.</strong> «Откуда» → «Куда» означает возможность дойти до следующей зацепки. Любого одного пути достаточно; условий AND/OR нет.</li><li><strong>Проверьте потерю.</strong> Пропустите одну улику или целый источник. Жёлтая рамка означает потерю пути относительно обычного хода. Выводы, недостижимые ещё до проверки, перечисляются отдельно. Циклы допустимы.</li><li><strong>Отметьте знания.</strong> «Раскрыто» участвует в снимке, «Не раскрыто» участвует только в планировании. «Недоступно» исключается из путей и снимка.</li><li><strong>Сделайте копии.</strong> JSON — полная копия с секретами. HTML — отдельные записи игроков. Данные кампании остаются в браузере, сайт их не отправляет.</li></ol><p>Передвиньте карточку мышью или задайте X/Y в форме. Обзор перемещается перетаскиванием фона и стрелками при фокусе на доске; масштаб — колесом, <kbd>+</kbd> и <kbd>−</kbd>. В «Списке» доступны те же материалы и связи.</p><p class="modal-note"><kbd>Ctrl+Z</kbd> отменяет действие, <kbd>Ctrl+Shift+Z</kbd> повторяет. В текстовых полях работают обычные команды редактора. История ограничена 60 действиями и сбрасывается после перезагрузки.</p>`);}

document.addEventListener('click',event=>{const node=event.target.closest('[data-node],[data-open-node]'),edge=event.target.closest('[data-edge],[data-open-edge]');if(suppressClick){suppressClick=false;return;}if(node)selectNode(node.dataset.node||node.dataset.openNode);else if(edge)selectEdge(edge.dataset.edge||edge.dataset.openEdge);});
$('#add-node').onclick=newNode;$('#add-edge').onclick=newEdge;$('#undo').onclick=()=>stepHistory('undo');$('#redo').onclick=()=>stepHistory('redo');$('#fit').onclick=fit;$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);$('#board-view').onclick=()=>changeView('board');$('#list-view').onclick=()=>changeView('list');$('#files-button').onclick=files;$('#player-button').onclick=exportPlayer;$('#help-button').onclick=help;
$('#case-title').onclick=()=>{if(!leaveEditor())return;modal('Название дела',`<form id="title-form" class="editor"><label>Название · попадёт в снимок игрокам<input name="title" maxlength="120" required value="${h(graph().title)}"></label><button class="primary">Сохранить</button></form>`);$('#title-form').onsubmit=e=>{e.preventDefault();const next=clone(graph());next.title=new FormData(e.currentTarget).get('title').trim();if(commit(next))$('#modal').close();};};
$('#failure-kind').onchange=()=>{const kind=$('#failure-kind').value, items=graph()[kind==='node'?'nodes':'edges'];failure=kind==='none'||!items.length?null:{kind:kind==='node'?'node':'edge',id:items[0].id};if(!items.length&&kind!=='none'){toast('Сначала добавьте материалы для проверки.');$('#failure-kind').value='none';}render();};$('#failure-item').onchange=()=>{failure={kind:$('#failure-kind').value==='node'?'node':'edge',id:$('#failure-item').value};render();};
$('#import-file').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>LIMITS.bytes){toast('Файл слишком большой: максимум 8 МБ.');return;}try{const next=parseGraph(await file.text());replace(next);}catch(e){toast(e.message);}};
document.addEventListener('keydown',event=>{if(event.target.closest('input,textarea,select,[contenteditable=true]')||$('#modal').open)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();stepHistory(event.shiftKey?'redo':'undo');}if(event.target===$('#board')){if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const d=60;camera.x+=event.key==='ArrowLeft'?d:event.key==='ArrowRight'?-d:0;camera.y+=event.key==='ArrowUp'?d:event.key==='ArrowDown'?-d:0;transformCamera();}if(event.key==='+'||event.key==='='){event.preventDefault();zoom(1.2);}if(event.key==='-'){event.preventDefault();zoom(1/1.2);}}});
$('#board').addEventListener('wheel',event=>{if(event.target.closest('.zoom-controls'))return;event.preventDefault();const rect=$('#board').getBoundingClientRect();zoom(event.deltaY<0?1.1:1/1.1,event.clientX-rect.left,event.clientY-rect.top);},{passive:false});
$('#board').addEventListener('pointerdown',event=>{if(drag||event.button!==0||event.target.closest('.zoom-controls,[data-edge]'))return;const button=event.target.closest('[data-node]');if(button&&dirty)return;const node=button?graph().nodes.find(n=>n.id===button.dataset.node):null;drag={pointerId:event.pointerId,kind:node?'node':'pan',id:node?.id,startX:event.clientX,startY:event.clientY,original:node?{x:node.x,y:node.y}:{x:camera.x,y:camera.y},moved:false};$('#board').setPointerCapture(event.pointerId);});
$('#board').addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.pointerId)return;const dx=event.clientX-drag.startX,dy=event.clientY-drag.startY;if(Math.abs(dx)+Math.abs(dy)<5&&!drag.moved)return;drag.moved=true;if(drag.kind==='pan'){camera.x=drag.original.x+dx;camera.y=drag.original.y+dy;transformCamera();}else{const x=Math.round(Math.max(-10000,Math.min(10000,drag.original.x+dx/camera.z))),y=Math.round(Math.max(-10000,Math.min(10000,drag.original.y+dy/camera.z)));drag.preview={x,y};const node=$(`[data-node="${drag.id}"]`);node.style.left=x+'px';node.style.top=y+'px';drawEdges();}});
function finishDrag(event,cancel=false){if(!drag||event.pointerId!==drag.pointerId)return;const finished=drag;drag=null;if($('#board').hasPointerCapture(event.pointerId))$('#board').releasePointerCapture(event.pointerId);if(finished.moved){suppressClick=true;setTimeout(()=>suppressClick=false,100);if(finished.kind==='node'){if(!cancel){const next=clone(graph());Object.assign(next.nodes.find(n=>n.id===finished.id),finished.preview);commit(next);}else render();}}else if(!cancel&&finished.kind==='node'){selectNode(finished.id);suppressClick=true;setTimeout(()=>suppressClick=false,100);}}
$('#board').addEventListener('pointerup',event=>finishDrag(event));$('#board').addEventListener('pointercancel',event=>finishDrag(event,true));
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
window.addEventListener('storage',event=>{if(event.key===storageKey)toast('Другая вкладка изменила это дело. Сохраните свою JSON-копию и перезагрузите, чтобы открыть её изменения.');});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(view==='board')fit();},200);});
if(innerWidth<=850){view='list';$('#board').hidden=true;$('#list').hidden=false;$('#board-view').setAttribute('aria-pressed','false');$('#list-view').setAttribute('aria-pressed','true');}
render();fit();if(restored)$('#saved').textContent='Восстановлено из этого браузера';if(storageError){$('#storage-note').textContent=storageError;$('#saved').textContent='Проверьте резервную копию';toast(storageError);}
